<?xml version="1.0" encoding="UTF-8"?>
<definitions xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://xmlns.example.com/1224493579125" xmlns:xsd="http://www.w3.org/2001/XMLSchema" targetNamespace="http://xmlns.example.com/1224493579125">
    <message name="MessageIn">
        <part name="customerName" type="xsd:string"/>
    </message>
    <message name="MessageOut">
        <part name="serviceId" type="xsd:string"/>
    </message>
    <message name="MessageFault">
        <part name="errorMessage" type="xsd:string"/>
    </message>
    <portType name="xAuthorityPortType">
        <operation name="CreateServiceOperation">
            <input message="tns:MessageIn"/>
            <output message="tns:MessageOut"/>
            <fault name="fault1" message="tns:MessageFault"/>
        </operation>
    </portType>
</definitions>