<?xml version="1.0" encoding="UTF-8"?>
<definitions xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:pfx1="http://www.tibco.com/CLEver/Lookup.xsd" xmlns:pfx0="http://www.tibco.com/CLEver/ExtraTypes" xmlns:ns="http://www.tibco.com/CLEver/FrontendServices/Transactional/Lookup/LookupInterfaceSpecs" xmlns:tns="http://www.tibco.com/CLEver/Transactional/Lookup" targetNamespace="http://www.tibco.com/CLEver/Transactional/Lookup">
    <import namespace="http://www.tibco.com/CLEver/Lookup.xsd" location="../../../../Shared Resources/Schema Definitions/CLEver/Lookup.xsd"/>
    <import namespace="http://www.tibco.com/CLEver/ExtraTypes" location="../../../../Shared Resources/Schema Definitions/CLEver/ExtraTypes.xsd"/>
    <import namespace="http://www.tibco.com/CLEver/FrontendServices/Transactional/Lookup/LookupInterfaceSpecs" location="LookupInterfaceSpecs.xsd"/>
    <message name="Lookup_Retrieve_Output">
        <part name="parameters" element="ns:Lookup_Retrieve_Output"/>
    </message>
    <message name="Lookup_Retrieve_Input">
        <part name="parameters" element="ns:Lookup_Retrieve_Input"/>
    </message>
    <portType name="Lookup">
        <operation name="Lookup_Retrieve">
            <input message="tns:Lookup_Retrieve_Input"/>
            <output message="tns:Lookup_Retrieve_Output"/>
        </operation>
    </portType>
</definitions>