<?xml version="1.0" encoding="UTF-8"?>
<definitions xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:ikk="urn:IKKAdapter.FindPropertyAddressAGOP" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" name="FindPropertyAddressAGOP" targetNamespace="urn:IKKAdapter.FindPropertyAddressAGOP">
    <types>
        <xsd:schema elementFormDefault="qualified" targetNamespace="urn:IKKAdapter.FindPropertyAddressAGOP">
            <xsd:include schemaLocation="../../XSDSchemas/IKKAdapter/Services/FindPropertyAddressAGOP.xsd"/>
            <xsd:element name="FindPropertyAddressAGOPRequest" type="ikk:FindPropertyAddressAGOPRequest"/>
            <xsd:element name="FindPropertyAddressAGOPResponse" type="ikk:FindPropertyAddressAGOPResponse"/>
        </xsd:schema>
    </types>
    <message name="FindPropertyAddressAGOPRequest">
        <part element="ikk:FindPropertyAddressAGOPRequest" name="parameters"/>
    </message>
    <message name="FindPropertyAddressAGOPResponse">
        <part element="ikk:FindPropertyAddressAGOPResponse" name="parameters"/>
    </message>
    <portType name="FindPropertyAddressAGOPPortType">
        <operation name="FindPropertyAddressAGOP">
            <input message="ikk:FindPropertyAddressAGOPRequest"/>
            <output message="ikk:FindPropertyAddressAGOPResponse"/>
        </operation>
    </portType>
    <binding name="FindPropertyAddressAGOPSoapBinding" type="ikk:FindPropertyAddressAGOPPortType">
        <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
        <operation name="FindPropertyAddressAGOP">
            <soap:operation style="document"/>
            <input>
                <soap:body use="literal"/>
            </input>
            <output>
                <soap:body use="literal"/>
            </output>
        </operation>
    </binding>
    <service name="FindPropertyAddressAGOPService">
        <port binding="ikk:FindPropertyAddressAGOPSoapBinding" name="FindPropertyAddressAGOPSoap">
            <soap:address location="http://localhost:8080/IKKAdapter/Processes/FindPropertyAddressAGOP"/>
        </port>
    </service>
</definitions>