<?xml version="1.0" encoding="UTF-8"?>
<definitions xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:ikk="urn:IKKAdapter.GetBillRecipient" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" name="GetBillRecipient" targetNamespace="urn:IKKAdapter.GetBillRecipient">
    <types>
        <xsd:schema elementFormDefault="qualified" targetNamespace="urn:IKKAdapter.GetBillRecipient">
            <xsd:include schemaLocation="../../XSDSchemas/IKKAdapter/Services/GetBillRecipient.xsd"/>
            <xsd:element name="GetBillRecipientRequest" type="ikk:GetBillRecipientRequest"/>
            <xsd:element name="GetBillRecipientResponse" type="ikk:GetBillRecipientResponse"/>
        </xsd:schema>
    </types>
    <message name="GetBillRecipientRequest">
        <part element="ikk:GetBillRecipientRequest" name="parameters"/>
    </message>
    <message name="GetBillRecipientResponse">
        <part element="ikk:GetBillRecipientResponse" name="parameters"/>
    </message>
    <portType name="GetBillRecipientPortType">
        <operation name="GetBillRecipient">
            <input message="ikk:GetBillRecipientRequest"/>
            <output message="ikk:GetBillRecipientResponse"/>
        </operation>
    </portType>
    <binding name="GetBillRecipientSoapBinding" type="ikk:GetBillRecipientPortType">
        <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
        <operation name="GetBillRecipient">
            <soap:operation style="document"/>
            <input>
                <soap:body use="literal"/>
            </input>
            <output>
                <soap:body use="literal"/>
            </output>
        </operation>
    </binding>
    <service name="GetBillRecipientService">
        <port binding="ikk:GetBillRecipientSoapBinding" name="GetBillRecipientSoap">
            <soap:address location="http://localhost:8080/IKKAdapter/Processes/GetBillRecipient"/>
        </port>
    </service>
</definitions>