<?xml version="1.0" encoding="UTF-8"?>
<definitions xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:ikk="urn:IKKAdapter.GetCustomerReference" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" name="GetCustomerReference" targetNamespace="urn:IKKAdapter.GetCustomerReference">
	<types>
		<xsd:schema elementFormDefault="qualified" targetNamespace="urn:IKKAdapter.GetCustomerReference">
			<xsd:include schemaLocation="../../XSDSchemas/IKKAdapter/Services/GetCustomerReference.xsd"/>
			<xsd:element name="GetCustomerReferenceRequest" type="ikk:GetCustomerReferenceRequest"/>
			<xsd:element name="GetCustomerReferenceResponse" type="ikk:GetCustomerReferenceResponse"/>
		</xsd:schema>
	</types>
	<message name="GetCustomerReferenceRequest">
		<part element="ikk:GetCustomerReferenceRequest" name="parameters"/>
	</message>
	<message name="GetCustomerReferenceResponse">
		<part element="ikk:GetCustomerReferenceResponse" name="parameters"/>
	</message>
	<portType name="GetCustomerReferencePortType">
		<operation name="GetCustomerReference">
			<input message="ikk:GetCustomerReferenceRequest"/>
			<output message="ikk:GetCustomerReferenceResponse"/>
		</operation>
	</portType>
	<binding name="GetCustomerReferenceSoapBinding" type="ikk:GetCustomerReferencePortType">
		<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
		<operation name="GetCustomerReference">
			<soap:operation style="document"/>
			<input>
				<soap:body use="literal"/>
			</input>
			<output>
				<soap:body use="literal"/>
			</output>
		</operation>
	</binding>
	<service name="GetCustomerReference">
		<port binding="ikk:GetCustomerReferenceSoapBinding" name="GetCustomerReferenceSoap">
			<soap:address location="http://localhost:8080/IKKAdapter/Processes/GetCustomerReference"/>
		</port>
	</service>
</definitions>
