<?xml version="1.0" encoding="UTF-8"?>
<definitions xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:ikk="urn:IKKAdapter.GetLineFacilities" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" name="GetLineFacilities" targetNamespace="urn:IKKAdapter.GetLineFacilities">
    <types>
        <xsd:schema elementFormDefault="qualified" targetNamespace="urn:IKKAdapter.GetLineFacilities">
            <xsd:include schemaLocation="../../XSDSchemas/IKKAdapter/Services/GetLineFacilities.xsd"/>
            <xsd:element name="GetLineFacilitiesRequest" type="ikk:GetLineFacilitiesRequest"/>
            <xsd:element name="GetLineFacilitiesResponse" type="ikk:GetLineFacilitiesResponse"/>
        </xsd:schema>
    </types>
    <message name="GetLineFacilitiesRequest">
        <part element="ikk:GetLineFacilitiesRequest" name="parameters"/>
    </message>
    <message name="GetLineFacilitiesResponse">
        <part element="ikk:GetLineFacilitiesResponse" name="parameters"/>
    </message>
    <portType name="GetLineFacilitiesPortType">
        <operation name="GetLineFacilities">
            <input message="ikk:GetLineFacilitiesRequest"/>
            <output message="ikk:GetLineFacilitiesResponse"/>
        </operation>
    </portType>
    <binding name="GetLineFacilitiesSoapBinding" type="ikk:GetLineFacilitiesPortType">
        <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
        <operation name="GetLineFacilities">
            <soap:operation style="document"/>
            <input>
                <soap:body use="literal"/>
            </input>
            <output>
                <soap:body use="literal"/>
            </output>
        </operation>
    </binding>
    <service name="GetLineFacilitiesService">
        <port binding="ikk:GetLineFacilitiesSoapBinding" name="GetLineFacilities">
            <soap:address location="http://localhost:8080/IKKAdapter/Processes/GetLineFacilities"/>
        </port>
    </service>
</definitions>