<?xml version="1.0" encoding="UTF-8"?>
<definitions xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:ikk="urn:IKKAdapter.ReportRevenueAvailability" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" name="ReportRevenueAvailability" targetNamespace="urn:IKKAdapter.ReportRevenueAvailability">
    <types>
        <xsd:schema elementFormDefault="qualified" targetNamespace="urn:IKKAdapter.ReportRevenueAvailability">
            <xsd:include schemaLocation="../../XSDSchemas/IKKAdapter/Services/ReportRevenueAvailability.xsd"/>
            <xsd:element name="ReportRevenueAvailabilityRequest" type="ikk:ReportRevenueAvailabilityRequest"/>
            <xsd:element name="ReportRevenueAvailabilityResponse" type="ikk:ReportRevenueAvailabilityResponse"/>
        </xsd:schema>
    </types>
    <message name="ReportRevenueAvailabilityRequest">
        <part element="ikk:ReportRevenueAvailabilityRequest" name="parameters"/>
    </message>
    <message name="ReportRevenueAvailabilityResponse">
        <part element="ikk:ReportRevenueAvailabilityResponse" name="parameters"/>
    </message>
    <portType name="ReportRevenueAvailabilityPortType">
        <operation name="ReportRevenueAvailability">
            <input message="ikk:ReportRevenueAvailabilityRequest"/>
            <output message="ikk:ReportRevenueAvailabilityResponse"/>
        </operation>
    </portType>
    <binding name="ReportRevenueAvailabilitySoapBinding" type="ikk:ReportRevenueAvailabilityPortType">
        <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
        <operation name="ReportRevenueAvailability">
            <soap:operation style="document"/>
            <input>
                <soap:body use="literal"/>
            </input>
            <output>
                <soap:body use="literal"/>
            </output>
        </operation>
    </binding>
    <service name="ReportRevenueAvailabilityService">
        <port binding="ikk:ReportRevenueAvailabilitySoapBinding" name="ReportRevenueAvailabilitySoap">
            <soap:address location="http://localhost:8080/IKKAdapter/Processes/ReportRevenueAvailability"/>
        </port>
    </service>
</definitions>