<?xml version="1.0" encoding="UTF-8"?>
<definitions xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://www.tibco.com/CLEver/FrontendServices/Security/Login" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:pfx0="http://www.tibco.com/CLEver/FrontendServices/Security/Login/LoginInterfaceSpecs" targetNamespace="http://www.tibco.com/CLEver/FrontendServices/Security/Login">
    <import namespace="http://www.tibco.com/CLEver/FrontendServices/Security/Login/LoginInterfaceSpecs" location="LoginInterfaceSpecs.xsd"/>
    <message name="Execute_Login_Input">
        <part element="pfx0:Execute_Login_Input" name="parameters"/>
    </message>
    <message name="Execute_Login_Output">
        <part element="pfx0:Execute_Login_Output" name="parameters"/>
    </message>
    <portType name="Login">
        <operation name="LoginOp">
            <input message="tns:Execute_Login_Input"/>
            <output message="tns:Execute_Login_Output"/>
        </operation>
    </portType>
</definitions>