<?xml version="1.0" encoding="UTF-8"?>
<definitions xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:ns="http://www.tibco.com/CLEver/FrontendServices/Transactional/Exception/ExceptionInterfaceSpecs" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:ns2="http://www.tibco.com/CLEver/FrontendServices/Transactional/Logging/LoggingInterfaceSpecs" xmlns:tns="http://www.tibco.com/CLEver/Transactional/Logging" targetNamespace="http://www.tibco.com/CLEver/Transactional/Logging">
    <import namespace="http://www.tibco.com/CLEver/FrontendServices/Transactional/Exception/ExceptionInterfaceSpecs" location="LoggingInterfaceSpecs.xsd"/>
    <message name="Retrieve_Logging_Input">
        <part name="part1" element="ns:Retrieve_Logging_Input"/>
    </message>
    <message name="Retrieve_Logging_Output">
        <part name="part1" element="ns:Retrieve_Logging_Output"/>
    </message>
    <portType name="Logging">
        <operation name="Retrieve">
            <input message="tns:Retrieve_Logging_Input"/>
            <output message="tns:Retrieve_Logging_Output"/>
        </operation>
    </portType>
</definitions>