BEGIN
	DECLARE @STARTDATE DATETIME;

	SELECT @STARTDATE = GETDATE();

	DELETE FROM TDA_LOGGINGLARGETEXT WHERE ID IN
	(SELECT ID FROM TDA_LOGGING WHERE DATETIME < @STARTDATE - 7)

	DELETE FROM TDA_LOGGING WHERE DATETIME < @STARTDATE - 7

	DELETE FROM TDA_EXCEPTIONLARGETEXT WHERE ID IN
	(SELECT DUMPANALYSIS FROM TDA_EXCEPTION WHERE DATETIME < @STARTDATE - 7)

	DELETE FROM TDA_EXCEPTION WHERE DATETIME < @STARTDATE - 7
END